// lib/constants.ts

export const SLOT_STATUS = {
  AVAILABLE: 'AVAILABLE',
  AVAILABLE_NEEDS_CONFIRM: 'AVAILABLE_NEEDS_CONFIRM',
  TEMP_LOCKED: 'TEMP_LOCKED',
  BOOKED: 'BOOKED',

  // 🟡 مرحلة انتقالية (اختياري)
  NEED_CONFIRMATION: 'AVAILABLE_NEEDS_CONFIRM'
} as const

export const BOOKING_STATUS = {
  PENDING_CONFIRMATION: 'PENDING_CONFIRMATION',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  FAILED: 'FAILED'
} as const

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED'
} as const

export const FIELD_STATUS = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  MAINTENANCE: 'MAINTENANCE'
} as const
