// lib/constants.ts
export const SLOT_STATUS = {
  AVAILABLE: 'AVAILABLE',
  TEMP_LOCKED: 'TEMP_LOCKED',
  NEED_CONFIRMATION: 'NEED_CONFIRMATION',
  BOOKED: 'BOOKED'
} as const

export const BOOKING_STATUS = {
  PENDING_CONFIRMATION: 'PENDING_CONFIRMATION',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  FAILED: 'FAILED'
} as const

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED'
} as const

export const FIELD_STATUS = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  MAINTENANCE: 'MAINTENANCE'
} as const
