// lib/core/errors/error-codes.ts
// ✅ ملف كامل - لا يحتاج تعديل
export const ERROR_CODES = {
  // Auth (1xx)
  UNAUTHORIZED: 'AUTH_001',
  INVALID_CREDENTIALS: 'AUTH_002',
  SESSION_EXPIRED: 'AUTH_003',
  
  // Validation (2xx)
  INVALID_INPUT: 'VAL_001',
  MISSING_FIELD: 'VAL_002',
  INVALID_DATE: 'VAL_003',
  
  // Slot (3xx)
  SLOT_NOT_FOUND: 'SLOT_001',
  SLOT_UNAVAILABLE: 'SLOT_002',
  SLOT_LOCKED_BY_OTHER: 'SLOT_003',
  SLOT_LOCK_EXPIRED: 'SLOT_004',
  SLOT_ALREADY_BOOKED: 'SLOT_005',
  SLOT_CANNOT_BE_LOCKED: 'SLOT_006',
  
  // Booking (4xx)
  BOOKING_NOT_FOUND: 'BOOK_001',
  BOOKING_NOT_OWNED: 'BOOK_002',
  BOOKING_INVALID_STATE: 'BOOK_003',
  BOOKING_LIMIT_EXCEEDED: 'BOOK_004',
  BOOKING_EXPIRED: 'BOOK_005',
  BOOKING_IN_PROGRESS: 'BOOK_006',
  
  // Payment (5xx)
  PAYMENT_ALREADY_PROCESSED: 'PAY_001',
  PAYMENT_FAILED: 'PAY_002',
  DUPLICATE_PAYMENT: 'PAY_003',
  PAYMENT_NOT_FOUND: 'PAY_004',
  
  // Time (6xx)
  TIME_IN_PAST: 'TIME_001',
  TIME_TOO_CLOSE: 'TIME_002',
  
  // Field (7xx)
  FIELD_NOT_FOUND: 'FIELD_001',
  FIELD_CLOSED: 'FIELD_002',
  FIELD_MAINTENANCE: 'FIELD_003',
  
  // System (9xx)
  INTERNAL_ERROR: 'SYS_001',
  RATE_LIMITED: 'SYS_002',
  SERVICE_UNAVAILABLE: 'SYS_003'
} as const

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES]