// app/layout.tsx أو app/page.tsx
import { startupCheck } from '@/lib/env/startup-check'

// في Server Component
await startupCheck()
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
